name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-26.04, windows-2022, macos-26]
        build_type: [release]
        c_compiler: [gcc, clang, cl]
        generator: ["Ninja Multi-Config", "Visual Studio 17 2022"]
        include:
          - os: ubuntu-26.04
            c_compiler: gcc
            cpp_compiler: g++
            generator: "Ninja Multi-Config"
          - os: windows-2022
            c_compiler: cl
            cpp_compiler: cl
            generator: "Visual Studio 17 2022"
          - os: macos-26
            c_compiler: clang
            cpp_compiler: clang++
            generator: "Ninja Multi-Config"
        exclude:
          - os: ubuntu-26.04
            c_compiler: cl
          - os: ubuntu-26.04
            c_compiler: clang
          - os: ubuntu-26.04
            generator: "Visual Studio 17 2022"
          - os: windows-2022
            c_compiler: clang
          - os: windows-2022
            c_compiler: gcc
          - os: windows-2022
            generator: "Ninja Multi-Config"
          - os: macos-26
            c_compiler: cl
          - os: macos-26
            c_compiler: gcc
          - os: macos-26
            generator: "Visual Studio 17 2022"

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install Conan
      run: pip install conan

    - name: Create default Conan profile
      run: conan profile detect --force

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake

    - name: Install Macos depencendies
      if: runner.os == 'Macos'
      run: |
        brew install llvm
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

    - name: Conan install
      run: conan install . --build=missing -c tools.cmake.cmaketoolchain:generator="${{ matrix.generator }}" -s:a compiler.cppstd=23

    - name: Configure CMake
      run: cmake --preset=conan-default

    - name: Build
      run: cmake --build --preset=conan-${{ matrix.build_type }}

    - name: Test
      run: ctest --preset=conan-${{ matrix.build_type }} -V
