name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: ./build/tests/test_pfadfinder
